/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";

declare let self: ServiceWorkerGlobalScope;

// Cleanup old cache versions automatically
cleanupOutdatedCaches();

// Precache static assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Web Push event listener
self.addEventListener("push", (event) => {
  let data: { title?: string; body?: string; icon?: string; badge?: string; url?: string } = {
    title: "PG Cashflow",
    body: "You have a new update.",
  };

  if (event.data) {
    try {
      data = event.data.json();
    } catch {
      data = { title: "PG Cashflow", body: event.data.text() };
    }
  }

  const options = {
    body: data.body || "",
    icon: "/pwa-192x192.png",
    badge: "/pwa-192x192.png",
    data: data.url || "/",
    vibrate: [200, 100, 200],
  } as unknown as NotificationOptions;

  event.waitUntil(self.registration.showNotification(data.title || "PG Cashflow", options));
});

// Notification click event listener
self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const urlToOpen = (event.notification.data as string) || "/";

  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((windowClients) => {
      for (const client of windowClients) {
        if (client.url.includes(urlToOpen) && "focus" in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
